stages:
- name: complier
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-service:1.1
      pushRemote: true
      registry: 10.110.1.141:30257
timeout: 160
notification: {}
