stages:
- name: complier
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34316
timeout: 160
notification: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml