stages:
- name: build
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build && echo "hello world!"
  when:
    event: {}
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jinshubao/hello-service:1.0
      pushRemote: true
      registry: index.docker.io
  - publishCatalogConfig:
      path: ./chart/hello-service/1.0
      catalogTemplate: hello-service
      version: "1.0"
      gitUrl: https://github.com/jinshubao/hello-service.git
      gitBranch: master
      gitAuthor: jinshubao
      gitEmail: jinshubao123@126.com
    envFrom:
    - sourceName: github
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: github
      sourceKey: PASSWORD
      targetKey: PASSWORD
  - applyAppConfig:
      catalogTemplate: hello-service
      version: "1.0"
      name: hello-service
      targetNamespace: default
timeout: 60
notification: {}
