stages:
- name: complier
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jinshubao/hello-service:1.2
      pushRemote: true
      registry: index.docker.io
timeout: 160
notification: {}
