stages:
- name: build
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build && echo "hello world!"
  when:
    event: {}
- name: image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-service:1.0
      registry: 127.0.0.1:34625
timeout: 60
notification: {}
