stages:
- name: complier
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-service:1.2
      pushRemote: true
      registry: 127.0.0.1:34625
timeout: 160
notification: {}
