stages:
- name: complier
  steps:
  - runScriptConfig:
      image: gradle:5.6.3-jdk8
      shellScript: gradle build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 127.0.0.1/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: 127.0.0.1:34316
timeout: 160
notification: {}
